# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sq_symbol', models.CharField(max_length=25)),
                ('sq_date', models.DateTimeField(verbose_name='date of quote')),
                ('sq_open', models.FloatField(default=0.0)),
                ('sq_high', models.FloatField(default=0.0)),
                ('sq_low', models.FloatField(default=0.0)),
                ('sq_close', models.FloatField(default=0.0)),
                ('sq_volume', models.IntegerField(default=0)),
            ],
        ),
    ]
